#!/usr/bin/env bash

APP="scripture" # name of your release

BUILD_HOST="hullubullu.de" # host where to build the release
BUILD_USER="scripture" # local user at build host
BUILD_AT="/tmp/scripture/builds" # build directory on build host

# STAGING_HOSTS="test2.acme.org" # staging / test hosts separated by space
# STAGING_USER="test" # local user at staging hosts
# TEST_AT="/test/my-erlang-app" # deploy directory on staging hosts. default is DELIVER_TO

PRODUCTION_HOSTS="hullubullu.de" # deploy / production hosts separated by space
PRODUCTION_USER="scripture" # local user at deploy hosts
DELIVER_TO="/opt/scripture" # deploy directory on production hosts

pre_erlang_get_and_update_deps() {
  __remote "
    set -e
    [ -f ~/.profile ] && source ~/.profile
    cd $BUILD_AT $SILENCE
    ln -s /home/scripture/prod.secret.exs config/prod.secret.exs
  "
}
